#!/usr/bin/env sh
# Print a curl timing breakdown (DNS, connect, TLS, TTFB, total) for a URL.
# Usage: benchurl <url> [curl options...]

set -eu

curl -so /dev/null -w "
  time_namelookup:  %{time_namelookup}\n\
     time_connect:  %{time_connect}\n\
  time_appconnect:  %{time_appconnect}\n\
 time_pretransfer:  %{time_pretransfer}\n\
    time_redirect:  %{time_redirect}\n\
time_starttransfer:  %{time_starttransfer}\n\
                   ----------\n\
       time_total:  %{time_total}\n" "$@"
