#!/usr/bin/env sh

set -eu

if command -v apt-get >/dev/null 2>&1; then
    sudo apt update -y && sudo apt upgrade -y
fi

if command -v yum >/dev/null 2>&1; then
    sudo yum update -y
fi

if command -v pacman >/dev/null 2>&1; then
    sudo pacman -Syu --noconfirm
fi

if command -v npm >/dev/null 2>&1; then
    npm cache clean && npm i -g && npm update -g
fi

if command -v composer >/dev/null 2>&1; then
    composer global update
fi

if command -v rustup >/dev/null 2>&1; then
    rustup update
fi

if command -v python >/dev/null 2>&1; then
    python -m pip install --user --upgrade pip
    python -m pip list --outdated --format=legacy | awk '{ print $1 }' | xargs -n1 pip install -U
fi

if command -v pyenv >/dev/null 2>&1; then
    pyenv update
fi

if command -v snap >/dev/null 2>&1; then
    sudo snap refresh
fi

if command -v cargo >/dev/null 2>&1; then
    if ! command -v cargo-update >/dev/null 2>&1; then
        cargo install cargo-update
    fi
    cargo install-update -a
fi

if [ -d "$HOME/.oh-my-zsh" ] && command -v omz >/dev/null 2>&1; then
    printf '\n'
    echo "Updating Oh My Zsh..."
    omz update
fi

if [ -d "$HOME/.tmux/plugins/tpm" ]; then
    printf '\n'
    echo "Updating Tmux plugins..."
    "$HOME/.tmux/plugins/tpm/bin/update_plugins" all
fi
