return {
  -- Portable package manager for Neovim that runs everywhere Neovim runs. Easily install and manage LSP servers, DAP servers, linters, and formatters.
  -- https://github.com/williamboman/mason.nvim
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "actionlint",
        "ansible-language-server",
        "ansible-lint",
        "antlers-language-server",
        "black",
        "bash-language-server",
        "blade-formatter",
        "css-lsp",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "dot-language-server",
        "efm",
        "emmet-ls",
        "eslint_d",
        "flake8",
        "hadolint",
        "html-lsp",
        "intelephense",
        "ltex-ls",
        "luacheck",
        "nginx-language-server",
        "php-debug-adapter",
        "phpstan",
        "pint",
        "prettierd",
        "pyright",
        "rustywind",
        "selene",
        "shellcheck",
        "shfmt",
        "stylua",
        "tailwindcss-language-server",
        "typescript-language-server",
        "vue-language-server",
      },
    },
  },
}
